// Command apigen writes the generated API clients from the engine's OpenAPI
// document (07 §7.3).
//
// The point is not convenience: it is that the engine, the Go client and the
// TypeScript client cannot describe the same endpoint differently. All three
// derive from internal/engineapi's route table, so a change to a DTO shows up
// in every surface or in none.
//
// Run with `make api`. `make api-check` regenerates into a temp dir and fails
// if the committed files differ — that check is what actually stops someone
// hand-editing a generated file, since a rule nobody enforces is a comment.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/jrullan/ducklab/internal/engineapi"
)

func main() {
	outDir := flag.String("out", ".", "repository root")
	specOnly := flag.Bool("spec-only", false, "write only the OpenAPI document")
	flag.Parse()

	doc := engineapi.BuildOpenAPI("0.3.0")

	specPath := filepath.Join(*outDir, "docs", "openapi.json")
	if err := writeJSON(specPath, doc); err != nil {
		fail(err)
	}
	fmt.Println("wrote", specPath)
	if *specOnly {
		return
	}

	tsPath := filepath.Join(*outDir, "frontend", "src", "api", "generated.ts")
	if err := os.WriteFile(tsPath, []byte(renderTS(doc)), 0o644); err != nil {
		fail(err)
	}
	fmt.Println("wrote", tsPath)
}

func fail(err error) {
	fmt.Fprintf(os.Stderr, "error: %v\n", err)
	os.Exit(1)
}

func writeJSON(path string, v any) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	data, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(data, '\n'), 0o644)
}

// --- TypeScript ---------------------------------------------------------------

func renderTS(doc map[string]any) string {
	var b strings.Builder
	b.WriteString(`// Code generated by cmd/apigen. DO NOT EDIT.
//
// Regenerate with: make api
//
// Hand-editing this file is a spec violation (07 §7.3): it exists so the
// engine, the Go client and this file cannot describe the same endpoint
// differently. An edit here would reintroduce exactly the drift it prevents.

`)

	components, _ := doc["components"].(map[string]any)
	schemas, _ := components["schemas"].(map[string]any)

	names := make([]string, 0, len(schemas))
	for name := range schemas {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		schema, _ := schemas[name].(map[string]any)
		b.WriteString(renderInterface(name, schema))
		b.WriteString("\n")
	}

	b.WriteString(renderOperations(doc))
	return b.String()
}

func renderInterface(name string, schema map[string]any) string {
	var b strings.Builder
	fmt.Fprintf(&b, "export interface %s {\n", name)

	props, _ := schema["properties"].(map[string]any)
	required := map[string]bool{}
	if list, ok := schema["required"].([]any); ok {
		for _, r := range list {
			required[fmt.Sprint(r)] = true
		}
	}

	keys := make([]string, 0, len(props))
	for k := range props {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, k := range keys {
		p, _ := props[k].(map[string]any)
		opt := ""
		if !required[k] {
			opt = "?"
		}
		fmt.Fprintf(&b, "  %s%s: %s;\n", tsKey(k), opt, tsType(p))
	}
	b.WriteString("}\n")
	return b.String()
}

func tsKey(k string) string {
	for _, c := range k {
		if !(c == '_' || (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9')) {
			return fmt.Sprintf("%q", k)
		}
	}
	return k
}

func tsType(p map[string]any) string {
	if ref, ok := p["$ref"].(string); ok {
		return ref[strings.LastIndex(ref, "/")+1:]
	}
	switch p["type"] {
	case "string":
		return "string"
	case "boolean":
		return "boolean"
	case "integer", "number":
		return "number"
	case "array":
		items, _ := p["items"].(map[string]any)
		return tsType(items) + "[]"
	case "object":
		if ap, ok := p["additionalProperties"].(map[string]any); ok {
			return "Record<string, " + tsType(ap) + ">"
		}
		return "Record<string, unknown>"
	}
	return "unknown"
}

type operation struct {
	id, method, path, reqType, resType string
	params                             []string
}

func renderOperations(doc map[string]any) string {
	paths, _ := doc["paths"].(map[string]any)
	var ops []operation

	pathKeys := make([]string, 0, len(paths))
	for p := range paths {
		pathKeys = append(pathKeys, p)
	}
	sort.Strings(pathKeys)

	for _, path := range pathKeys {
		item, _ := paths[path].(map[string]any)
		methods := make([]string, 0, len(item))
		for m := range item {
			methods = append(methods, m)
		}
		sort.Strings(methods)

		for _, m := range methods {
			op, _ := item[m].(map[string]any)
			id, _ := op["operationId"].(string)
			if id == "" {
				continue
			}
			o := operation{id: id, method: strings.ToUpper(m), path: path}
			for _, raw := range asSlice(op["parameters"]) {
				if p, ok := raw.(map[string]any); ok && p["in"] == "path" {
					o.params = append(o.params, fmt.Sprint(p["name"]))
				}
			}
			if rb, ok := op["requestBody"].(map[string]any); ok {
				o.reqType = schemaTypeOf(rb["content"])
			}
			if resps, ok := op["responses"].(map[string]any); ok {
				if r200, ok := resps["200"].(map[string]any); ok {
					o.resType = schemaTypeOf(r200["content"])
				}
			}
			ops = append(ops, o)
		}
	}

	var b strings.Builder
	b.WriteString(`
/** Every endpoint, derived from the engine's route table. */
export const OPERATIONS = [
`)
	for _, o := range ops {
		fmt.Fprintf(&b, "  { id: %q, method: %q, path: %q },\n", o.id, o.method, o.path)
	}
	b.WriteString("] as const;\n")
	return b.String()
}

func schemaTypeOf(content any) string {
	c, ok := content.(map[string]any)
	if !ok {
		return ""
	}
	j, ok := c["application/json"].(map[string]any)
	if !ok {
		return ""
	}
	s, ok := j["schema"].(map[string]any)
	if !ok {
		return ""
	}
	return tsType(s)
}

func asSlice(v any) []any {
	s, _ := v.([]any)
	return s
}
