// Code generated by cmd/apigen. DO NOT EDIT.
//
// Regenerate with: make api
//
// Hand-editing this file is a spec violation (07 §7.3): it exists so the
// engine, the Go client and this file cannot describe the same endpoint
// differently. An edit here would reintroduce exactly the drift it prevents.

export interface ArtifactNode {
  down?: string[];
  id?: string;
  kind?: string;
  title?: string;
  up?: string[];
}

export interface BudgetBudget {
  max_tokens?: number;
  max_turns?: number;
  max_usd?: number;
  max_wallclock_s?: number;
}

export interface BugAuditEntry {
  actor?: string;
  bug?: string;
  from?: string;
  note?: string;
  to?: string;
  ts?: string;
  via?: string;
}

export interface BugBug {
  attachments?: string[];
  body?: string;
  created_at?: string;
  duplicate_of?: string;
  history?: BugAuditEntry[];
  id?: string;
  next?: string[];
  reporter?: string;
  severity?: string;
  source?: string;
  status?: string;
  task_id?: string;
  title?: string;
  updated_at?: string;
}

export interface ConfigBudget {
  max_tokens?: number;
  max_turns?: number;
  max_usd?: number;
  max_wallclock_s?: number;
}

export interface ConfigCaps {
  context_tokens?: number;
  json_mode?: boolean;
  native_tools?: boolean;
  vision?: boolean;
}

export interface ConfigCost {
  input_per_mtok?: number;
  output_per_mtok?: number;
}

export interface ConfigExternalIndex {
  agentic_score?: number;
  as_of?: string;
  coding_score?: number;
  intelligence_score?: number;
  source?: string;
}

export interface ConfigGit {
  base_branch?: string;
  branch_prefix?: string;
  commit_trailer?: boolean;
  protected_paths?: string[];
}

export interface ConfigGitHub {
  enabled?: boolean;
  mirror_bugs?: boolean;
  repo?: string;
}

export interface ConfigInstall {
  command?: string;
  timeout_s?: number;
}

export interface ConfigProject {
  autonomy?: string;
  budget?: ConfigBudget;
  created?: string;
  describe?: string;
  git?: ConfigGit;
  github?: ConfigGitHub;
  id?: string;
  install?: ConfigInstall;
  mode_seats?: Record<string, Record<string, string[]>>;
  modes?: Record<string, string>;
  name?: string;
  roster?: Record<string, string>;
  roster_seats?: Record<string, string[]>;
  run?: ConfigRunApp;
  schema?: number;
  shell?: ConfigShellPolicy;
  verify?: ConfigVerify;
}

export interface ConfigRunApp {
  command?: string;
  health?: string;
  preflight?: string;
  requires?: string;
  url?: string;
}

export interface ConfigSamplingParams {
  disable_thinking?: boolean;
  max_tokens?: number;
  stop?: string[];
  temperature?: number;
  top_p?: number;
}

export interface ConfigShellPolicy {
  allow_prefixes?: string[];
  deny?: string[];
  mode?: string;
  network?: string;
  timeout_s?: number;
}

export interface ConfigVerify {
  build?: string;
  custom?: string;
  link_deps?: string[];
  lint?: string;
  mode?: string;
  setup?: string;
  test_globs?: string[];
  tests?: string;
  timeout_s?: number;
}

export interface DucklingCapabilities {
  context_tokens?: number;
  json_mode?: boolean;
  native_tools?: boolean;
  probed_at?: string;
  vision?: boolean;
}

export interface DucklingDuckling {
  caps?: DucklingCapabilities;
  color?: number;
  cost?: ConfigCost;
  fallback?: string;
  id?: string;
  model?: string;
  notes?: string;
  params?: ConfigSamplingParams;
  provider?: string;
  roles?: string[];
}

export interface EngineapiacceptRequest {
  message?: string;
}

export interface EngineapianswerRequest {
  answer?: string;
  question_id?: string;
}

export interface EngineapiattachRequest {
  data?: string;
  filename?: string;
}

export interface EngineapibenchRequest {
  ducklings?: string[];
  keep?: boolean;
  modes?: string[];
  suite?: string;
}

export interface EngineapibugItems {
  items?: BugBug[];
}

export interface EngineapicandidateCriteriaRequest {
  criteria?: Record<string, string[]>;
}

export interface EngineapichatSendRequest {
  message?: string;
}

export interface EngineapidiffResponse {
  diff?: string;
  tests?: string;
  warning?: string;
}

export interface EngineapiducklingTestRequest {
  prompt?: string;
  stream?: boolean;
}

export interface EngineapiducklingTestResponse {
  cost_usd?: number;
  text?: string;
  tokens_in?: number;
  tokens_out?: number;
}

export interface EngineapihealthResponse {
  ok?: boolean;
  provenance?: string;
  queue?: Record<string, number>;
  uptime_s?: number;
  version?: string;
}

export interface EngineapiliftRequest {
  kind?: string;
}

export interface EngineapirejectRequest {
  reason?: string;
}

export interface EngineapirenderedResponse {
  rendered?: string;
}

export interface EngineapirestartRequest {
  requester?: string;
}

export interface EngineapirosterSetRequest {
  duckling?: string;
  ducklings?: string[];
  mode?: string;
  role?: string;
}

export interface EngineapiskillNewRequest {
  name?: string;
  runnable?: boolean;
}

export interface EngineapiskillRunRequest {
  args?: Record<string, unknown>;
}

export interface EngineapitraceCheckResponse {
  errors?: Record<string, string>[];
}

export interface EngineapitranscriptResponse {
  markdown?: string;
}

export interface EngineapiverifyResponse {
  output?: string;
}

export interface ReportDelta {
  key?: string;
  n?: number;
  one_run?: boolean;
  pass_rate?: number;
  points_vs_baseline?: number;
}

export interface ReportReport {
  baseline?: string;
  by?: string;
  deltas?: ReportDelta[];
  resolutions?: ReportResolution[];
  rows?: ReportRow[];
  since?: string;
}

export interface ReportResolution {
  count?: number;
  kind?: string;
}

export interface ReportRow {
  builds?: number;
  cost_usd?: number;
  estimated?: boolean;
  failed?: number;
  key?: string;
  no_change_passes?: number;
  no_changes?: number;
  passed?: number;
  runs?: number;
  tokens?: number;
  unverified?: number;
  wallclock_ms?: number;
}

export interface RunlogBudgetLimits {
  tokens?: number;
  turns?: number;
  usd?: number;
  wallclock_s?: number;
}

export interface RunlogBudgetState {
  limit?: RunlogBudgetLimits;
  tokens?: number;
  turns?: number;
  usd?: number;
  wallclock_s?: number;
}

export interface RunlogDucklingSpend {
  calls?: number;
  cost_usd?: number;
  estimated?: boolean;
  tokens?: number;
}

export interface RunlogEvent {
  data?: Record<string, unknown>;
  duckling?: string;
  role?: string;
  round?: number;
  run_id?: string;
  seq?: number;
  ts?: string;
  turn?: number;
  type?: string;
}

export interface RunlogGateReproduction {
  command?: string;
  duration_s?: number;
  exit_code?: number;
  gate?: string;
  green?: boolean;
  output?: string;
}

export interface RunlogRedoNote {
  advisor?: string;
  draft?: string;
  editable?: boolean;
}

export interface RunlogRun {
  acceptance_gate?: RunlogGateReproduction;
  accepted?: boolean;
  agent_turns?: number;
  autonomy?: string;
  branch?: string;
  budget?: RunlogBudgetState;
  chain_build?: Record<string, unknown>;
  commit_sha?: string;
  dry_run?: boolean;
  ended_at?: string;
  failure?: string;
  gate?: string;
  id?: string;
  mode?: string;
  mode_source?: string;
  next?: string[];
  no_changes?: boolean;
  note?: string;
  origin?: string;
  pending_data?: Record<string, unknown>;
  pending_kind?: string;
  pending_since?: string;
  prior_accepted_sha?: string;
  project_id?: string;
  redo_note?: RunlogRedoNote;
  resolution?: string;
  revert_sha?: string;
  roster?: Record<string, string>;
  roster_sources?: Record<string, string>;
  spend?: Record<string, RunlogDucklingSpend>;
  stage?: string;
  stage_request?: Record<string, unknown>;
  started_at?: string;
  status?: string;
  stream?: boolean;
  subject?: string;
  task_body_hash?: string;
  task_id?: string;
  tests_modified?: boolean;
  tokens_estimated?: boolean;
  tree_snapshot?: string;
  tree_snapshot_head?: string;
  unsafe_writes?: boolean;
  verdict?: string;
  wallclock_ms?: number;
  warning?: string;
}

export interface ServiceAcceptResult {
  commit_sha?: string;
}

export interface ServiceAppStatus {
  command?: string;
  configured?: boolean;
  exit_error?: string;
  health?: string;
  log_tail?: string;
  pid?: number;
  preflight?: string;
  requires?: string;
  running?: boolean;
  started_at?: string;
  url?: string;
}

export interface ServiceAutopilotDefaultsView {
  autonomy?: string;
  max_fails?: number;
  max_tasks?: number;
}

export interface ServiceBenchEvidence {
  cost?: number;
  estimated?: boolean;
  score?: number;
  started_at?: string;
  suite?: string;
  suite_version?: number;
  tokens?: number;
  verdict?: string;
  wallclock?: number;
}

export interface ServiceBenchSummary {
  cells?: number;
  errors?: number;
  passed?: number;
  stamp?: string;
  started_at?: string;
  suite?: string;
  suite_version?: number;
}

export interface ServiceBudgetView {
  max_tokens?: number;
  max_turns?: number;
  max_usd?: number;
  max_wallclock_s?: number;
}

export interface ServiceBugRequest {
  body?: string;
  reporter?: string;
  severity?: string;
  source?: string;
  title?: string;
}

export interface ServiceCandidate {
  id?: string;
  why?: string;
}

export interface ServiceCandidateCriteriaView {
  catalog?: ServiceCriterion[];
  configured?: string[];
  criteria?: Record<string, string[]>;
  defaults?: Record<string, string[]>;
}

export interface ServiceCandidateView {
  diff?: string;
  gate?: string;
  label?: string;
}

export interface ServiceChatStartRequest {
  about_id?: string;
  about_kind?: string;
  duckling?: string;
  message?: string;
}

export interface ServiceCriterion {
  direction?: string;
  key?: string;
  label?: string;
  source?: string;
}

export interface ServiceDucklingView {
  caps?: ConfigCaps;
  color?: number;
  cost?: ConfigCost;
  fallback?: string;
  id?: string;
  model?: string;
  notes?: string;
  params?: ConfigSamplingParams;
  provider?: string;
  roles?: string[];
}

export interface ServiceGateResult {
  command?: string;
  duration_s?: number;
  exit_code?: number;
  gate?: string;
  green?: boolean;
  output?: string;
}

export interface ServiceGateStatus {
  adoptable?: boolean;
  best_verdict?: string;
  command?: string;
  detected?: string;
  detected_command?: string;
  link_deps?: string[];
  mode?: string;
  setup?: string;
}

export interface ServiceInitRequest {
  describe?: string;
  git_init?: boolean;
  name?: string;
  path?: string;
}

export interface ServiceInstallResult {
  command?: string;
  exit_code?: number;
  ok?: boolean;
  output?: string;
  seconds?: number;
}

export interface ServiceMeasuredEvidence {
  avg_cost_usd?: number;
  avg_wallclock_s?: number;
  estimated?: boolean;
  pass_rate?: number;
  runs?: number;
  tokens?: number;
}

export interface ServiceModeDefaultsView {
  agent_max_turns?: number;
  build_mode?: string;
  ducklings?: Record<string, string[]>;
  mode_seats?: Record<string, Record<string, string[]>>;
  role_pins?: Record<string, string[]>;
  role_turns?: Record<string, number>;
  rounds?: Record<string, number>;
  script_role_turns?: Record<string, number>;
  script_rounds?: Record<string, number>;
  seats?: Record<string, number>;
  test_mode?: string;
}

export interface ServiceNextStep {
  action?: string;
  id?: string;
  kind?: string;
  reason?: string;
  ref?: string;
  refs?: string[];
}

export interface ServiceProject {
  autonomy?: string;
  config?: ConfigProject;
  gate?: string;
  has_code?: boolean;
  id?: string;
  missing?: boolean;
  name?: string;
  path?: string;
}

export interface ServiceProviderView {
  api_key_env?: string;
  base_url?: string;
  headers?: Record<string, string>;
  id?: string;
  in_use?: string[];
  key_present?: boolean;
  kind?: string;
}

export interface ServiceReleaseRequest {
  bump?: string;
  revise?: string;
}

export interface ServiceReviewRequest {
  mode?: string;
  task_id?: string;
}

export interface ServiceRosterEntry {
  candidates?: ServiceCandidate[];
  default?: string;
  duckling?: string;
  ducklings?: string[];
  role?: string;
  source?: string;
}

export interface ServiceRosterView {
  entries?: ServiceRosterEntry[];
  warning?: string;
}

export interface ServiceRunDetail {
  events?: RunlogEvent[];
  run?: RunlogRun;
}

export interface ServiceRunRequest {
  agent_turns?: number;
  autonomy?: string;
  budget?: BudgetBudget;
  dry_run?: boolean;
  ducklings?: string[];
  mode?: string;
  no_stream?: boolean;
  note?: string;
  origin?: string;
  parallel?: boolean;
  redo?: boolean;
  rounds?: number;
  task_id?: string;
  unsafe_writes?: boolean;
  verify?: string;
}

export interface ServiceScorecard {
  bench?: Record<string, ServiceBenchEvidence>;
  caps?: ConfigCaps;
  cost?: ConfigCost;
  id?: string;
  index?: ConfigExternalIndex;
  locality?: string;
  measured?: ServiceMeasuredEvidence;
  measured_by_role?: Record<string, ServiceMeasuredEvidence>;
  model?: string;
  notes?: string;
  provider?: string;
  roles?: string[];
}

export interface ServiceSkillSummary {
  args?: SkillArg[];
  description?: string;
  name?: string;
  pending?: boolean;
  problems?: string[];
  runnable?: boolean;
  scope?: string;
  version?: number;
}

export interface ServiceStageRequest {
  adopt?: boolean;
  agent_turns?: number;
  autonomy?: string;
  ducklings?: string[];
  extend?: string;
  from?: string;
  images?: string[];
  mode?: string;
  revise?: string;
  rounds?: number;
  settle?: boolean;
  stage?: string;
  stream?: boolean;
}

export interface ServiceStatus {
  accepted_unreleased?: number;
  active_runs?: number;
  budget_spent_today?: number;
  provenance?: string;
  stage_progress?: Record<string, string>;
  task_counts?: Record<string, number>;
  unreleased_branches?: number;
  working_tree_dirty?: boolean;
}

export interface ServiceSuggestion {
  cost_per_mtok?: number;
  duckling?: string;
  evidence?: string;
  pass_rate?: number;
  role?: string;
  runs?: number;
}

export interface ServiceTaskView {
  blocked?: string;
  body?: string;
  branch?: string;
  build_only?: boolean;
  complexity?: string;
  depends_on?: string[];
  id?: string;
  implements?: string[];
  milestone?: string;
  next?: string[];
  spec_debt?: boolean;
  status?: string;
  test_ready?: boolean;
  title?: string;
  waiting?: string;
}

export interface ServiceTestFirstRequest {
  agent_turns?: number;
  build?: ServiceRunRequest;
  duckling?: string;
  ducklings?: string[];
  mode?: string;
  note?: string;
  origin?: string;
  redo?: boolean;
  task_id?: string;
  then_build?: boolean;
  verify?: string;
}

export interface SkillArg {
  name?: string;
  required?: boolean;
  type?: string;
}


/** Every endpoint, derived from the engine's route table. */
export const OPERATIONS = [
  { id: "BenchList", method: "GET", path: "/v1/bench" },
  { id: "Bench", method: "POST", path: "/v1/bench" },
  { id: "BenchStart", method: "POST", path: "/v1/bench/start" },
  { id: "BenchGet", method: "GET", path: "/v1/bench/{suite}/{stamp}" },
  { id: "AutopilotDefaults", method: "GET", path: "/v1/defaults/autopilot" },
  { id: "AutopilotDefaultsSet", method: "PUT", path: "/v1/defaults/autopilot" },
  { id: "BudgetDefaults", method: "GET", path: "/v1/defaults/budget" },
  { id: "BudgetDefaultsSet", method: "PUT", path: "/v1/defaults/budget" },
  { id: "CandidateCriteria", method: "GET", path: "/v1/defaults/candidates" },
  { id: "CandidateCriteriaSet", method: "PUT", path: "/v1/defaults/candidates" },
  { id: "ModeDefaults", method: "GET", path: "/v1/defaults/modes" },
  { id: "ModeDefaultsSet", method: "PUT", path: "/v1/defaults/modes" },
  { id: "GlobalRosterGet", method: "GET", path: "/v1/defaults/roster" },
  { id: "GlobalRosterSet", method: "PUT", path: "/v1/defaults/roster" },
  { id: "DucklingList", method: "GET", path: "/v1/ducklings" },
  { id: "Scorecards", method: "GET", path: "/v1/ducklings/scorecards" },
  { id: "DucklingRemove", method: "DELETE", path: "/v1/ducklings/{id}" },
  { id: "DucklingSet", method: "PUT", path: "/v1/ducklings/{id}" },
  { id: "DucklingProbe", method: "POST", path: "/v1/ducklings/{id}/probe" },
  { id: "DucklingTest", method: "POST", path: "/v1/ducklings/{id}/test" },
  { id: "Engine", method: "GET", path: "/v1/engine" },
  { id: "get_events", method: "GET", path: "/v1/events" },
  { id: "Health", method: "GET", path: "/v1/health" },
  { id: "ProjectList", method: "GET", path: "/v1/projects" },
  { id: "ProjectInit", method: "POST", path: "/v1/projects" },
  { id: "ProjectForget", method: "DELETE", path: "/v1/projects/{id}" },
  { id: "ProjectGet", method: "GET", path: "/v1/projects/{id}" },
  { id: "ProjectUpdate", method: "PATCH", path: "/v1/projects/{id}" },
  { id: "AppStatus", method: "GET", path: "/v1/projects/{id}/app" },
  { id: "AppStart", method: "POST", path: "/v1/projects/{id}/app/start" },
  { id: "AppStop", method: "POST", path: "/v1/projects/{id}/app/stop" },
  { id: "ArtifactGet", method: "GET", path: "/v1/projects/{id}/artifacts/{kind}" },
  { id: "ArtifactPromote", method: "POST", path: "/v1/projects/{id}/artifacts/{kind}/promote" },
  { id: "ArtifactDiscard", method: "DELETE", path: "/v1/projects/{id}/artifacts/{kind}/proposal" },
  { id: "ProjectAutonomy", method: "GET", path: "/v1/projects/{id}/autonomy" },
  { id: "ProjectAutonomySet", method: "PUT", path: "/v1/projects/{id}/autonomy" },
  { id: "AutopilotStatus", method: "GET", path: "/v1/projects/{id}/autopilot" },
  { id: "AutopilotSet", method: "POST", path: "/v1/projects/{id}/autopilot" },
  { id: "BugList", method: "GET", path: "/v1/projects/{id}/bugs" },
  { id: "BugAdd", method: "POST", path: "/v1/projects/{id}/bugs" },
  { id: "BugTriage", method: "POST", path: "/v1/projects/{id}/bugs/triage" },
  { id: "BugGet", method: "GET", path: "/v1/projects/{id}/bugs/{bug}" },
  { id: "BugEdit", method: "PUT", path: "/v1/projects/{id}/bugs/{bug}" },
  { id: "BugAttach", method: "POST", path: "/v1/projects/{id}/bugs/{bug}/attachments" },
  { id: "BugAttachment", method: "GET", path: "/v1/projects/{id}/bugs/{bug}/attachments/{name}" },
  { id: "BugPromote", method: "POST", path: "/v1/projects/{id}/bugs/{bug}/promote" },
  { id: "BugMove", method: "POST", path: "/v1/projects/{id}/bugs/{bug}/status" },
  { id: "ChatStart", method: "POST", path: "/v1/projects/{id}/chats" },
  { id: "ProjectGate", method: "GET", path: "/v1/projects/{id}/gate" },
  { id: "ProjectGateAdopt", method: "POST", path: "/v1/projects/{id}/gate" },
  { id: "GateRun", method: "POST", path: "/v1/projects/{id}/gate/run" },
  { id: "ProjectInstall", method: "POST", path: "/v1/projects/{id}/install" },
  { id: "ProjectNext", method: "GET", path: "/v1/projects/{id}/next" },
  { id: "ProjectRecover", method: "POST", path: "/v1/projects/{id}/recover/{action}" },
  { id: "ReleaseList", method: "GET", path: "/v1/projects/{id}/releases" },
  { id: "ReleasePlan", method: "POST", path: "/v1/projects/{id}/releases" },
  { id: "ReleaseGet", method: "GET", path: "/v1/projects/{id}/releases/{version}" },
  { id: "ReleaseCut", method: "POST", path: "/v1/projects/{id}/releases/{version}/cut" },
  { id: "Report", method: "GET", path: "/v1/projects/{id}/report" },
  { id: "ReviewList", method: "GET", path: "/v1/projects/{id}/reviews" },
  { id: "ReviewStart", method: "POST", path: "/v1/projects/{id}/reviews" },
  { id: "ReviewGet", method: "GET", path: "/v1/projects/{id}/reviews/{task}" },
  { id: "RosterUnpin", method: "DELETE", path: "/v1/projects/{id}/roster" },
  { id: "RosterGet", method: "GET", path: "/v1/projects/{id}/roster" },
  { id: "RosterSet", method: "PUT", path: "/v1/projects/{id}/roster" },
  { id: "RosterSuggest", method: "GET", path: "/v1/projects/{id}/roster/suggest" },
  { id: "RosterApply", method: "POST", path: "/v1/projects/{id}/roster/suggest" },
  { id: "RunStart", method: "POST", path: "/v1/projects/{id}/runs" },
  { id: "SkillList", method: "GET", path: "/v1/projects/{id}/skills" },
  { id: "SkillNew", method: "POST", path: "/v1/projects/{id}/skills" },
  { id: "SkillGet", method: "GET", path: "/v1/projects/{id}/skills/{name}" },
  { id: "SkillRun", method: "POST", path: "/v1/projects/{id}/skills/{name}/run" },
  { id: "StageStart", method: "POST", path: "/v1/projects/{id}/stages/{stage}" },
  { id: "ProjectStatus", method: "GET", path: "/v1/projects/{id}/status" },
  { id: "TaskList", method: "GET", path: "/v1/projects/{id}/tasks" },
  { id: "TaskNext", method: "GET", path: "/v1/projects/{id}/tasks/next" },
  { id: "TaskRemove", method: "DELETE", path: "/v1/projects/{id}/tasks/{task}" },
  { id: "TestRetire", method: "POST", path: "/v1/projects/{id}/tasks/{task}/retire-test" },
  { id: "TestStart", method: "POST", path: "/v1/projects/{id}/tests" },
  { id: "TraceCheck", method: "GET", path: "/v1/projects/{id}/trace/check" },
  { id: "TraceReport", method: "GET", path: "/v1/projects/{id}/trace/report" },
  { id: "TraceShow", method: "GET", path: "/v1/projects/{id}/trace/{anyID}" },
  { id: "ProviderList", method: "GET", path: "/v1/providers" },
  { id: "ProviderRemove", method: "DELETE", path: "/v1/providers/{id}" },
  { id: "ProviderSet", method: "PUT", path: "/v1/providers/{id}" },
  { id: "Restart", method: "POST", path: "/v1/restart" },
  { id: "RunList", method: "GET", path: "/v1/runs" },
  { id: "RunGet", method: "GET", path: "/v1/runs/{id}" },
  { id: "RunAbort", method: "POST", path: "/v1/runs/{id}/abort" },
  { id: "RunAccept", method: "POST", path: "/v1/runs/{id}/accept" },
  { id: "RunAnswer", method: "POST", path: "/v1/runs/{id}/answer" },
  { id: "RunBrief", method: "GET", path: "/v1/runs/{id}/brief" },
  { id: "RunBudgetLift", method: "POST", path: "/v1/runs/{id}/budget/lift" },
  { id: "RunCandidates", method: "GET", path: "/v1/runs/{id}/candidates" },
  { id: "ChatSend", method: "POST", path: "/v1/runs/{id}/chat" },
  { id: "ChatEnd", method: "POST", path: "/v1/runs/{id}/chat/end" },
  { id: "RunDiff", method: "GET", path: "/v1/runs/{id}/diff" },
  { id: "RunFileFindings", method: "POST", path: "/v1/runs/{id}/findings/file" },
  { id: "RunLLM", method: "GET", path: "/v1/runs/{id}/llm" },
  { id: "RunReject", method: "POST", path: "/v1/runs/{id}/reject" },
  { id: "RunReseat", method: "POST", path: "/v1/runs/{id}/reseat" },
  { id: "RunResume", method: "POST", path: "/v1/runs/{id}/resume" },
  { id: "RunTranscript", method: "GET", path: "/v1/runs/{id}/transcript" },
  { id: "RunVerify", method: "GET", path: "/v1/runs/{id}/verify" },
  { id: "post_shutdown", method: "POST", path: "/v1/shutdown" },
] as const;
