// Code generated by cmd/apigen. DO NOT EDIT.
//
// Regenerate with: make api
//
// Hand-editing this file is a spec violation (07 §7.3): it exists so the
// engine, the Go client and this file cannot describe the same endpoint
// differently. An edit here would reintroduce exactly the drift it prevents.

export interface ArtifactNode {
  down?: string[];
  id?: string;
  kind?: string;
  title?: string;
  up?: string[];
}

export interface BudgetBudget {
  max_tokens?: number;
  max_turns?: number;
  max_usd?: number;
  max_wallclock_s?: number;
}

export interface ConfigBudget {
  max_tokens?: number;
  max_turns?: number;
  max_usd?: number;
  max_wallclock_s?: number;
}

export interface ConfigCaps {
  context_tokens?: number;
  native_tools?: boolean;
}

export interface ConfigCost {
  input_per_mtok?: number;
  output_per_mtok?: number;
}

export interface ConfigGit {
  base_branch?: string;
  branch_prefix?: string;
  commit_trailer?: boolean;
  protected_paths?: string[];
}

export interface ConfigGitHub {
  enabled?: boolean;
  mirror_bugs?: boolean;
  repo?: string;
}

export interface ConfigProject {
  autonomy?: string;
  budget?: ConfigBudget;
  created?: string;
  describe?: string;
  git?: ConfigGit;
  github?: ConfigGitHub;
  id?: string;
  modes?: Record<string, string>;
  name?: string;
  roster?: Record<string, string>;
  schema?: number;
  shell?: ConfigShellPolicy;
  verify?: ConfigVerify;
}

export interface ConfigSamplingParams {
  disable_thinking?: boolean;
  max_tokens?: number;
  stop?: string[];
  temperature?: number;
  top_p?: number;
}

export interface ConfigShellPolicy {
  allow_prefixes?: string[];
  deny?: string[];
  mode?: string;
  network?: string;
  timeout_s?: number;
}

export interface ConfigVerify {
  build?: string;
  custom?: string;
  lint?: string;
  mode?: string;
  test_globs?: string[];
  tests?: string;
  timeout_s?: number;
}

export interface DucklingCapabilities {
  context_tokens?: number;
  json_mode?: boolean;
  native_tools?: boolean;
  probed_at?: string;
  vision?: boolean;
}

export interface DucklingDuckling {
  caps?: DucklingCapabilities;
  color?: number;
  cost?: ConfigCost;
  id?: string;
  model?: string;
  notes?: string;
  params?: ConfigSamplingParams;
  provider?: string;
  roles?: string[];
}

export interface EngineapiacceptRequest {
  message?: string;
}

export interface EngineapianswerRequest {
  answer?: string;
  question_id?: string;
}

export interface EngineapibenchRequest {
  ducklings?: string[];
  keep?: boolean;
  modes?: string[];
  suite?: string;
}

export interface EngineapidiffResponse {
  diff?: string;
  tests?: string;
  warning?: string;
}

export interface EngineapiducklingTestRequest {
  prompt?: string;
  stream?: boolean;
}

export interface EngineapiducklingTestResponse {
  cost_usd?: number;
  text?: string;
  tokens_in?: number;
  tokens_out?: number;
}

export interface EngineapihealthResponse {
  active_runs?: number;
  ok?: boolean;
  uptime_s?: number;
  version?: string;
}

export interface EngineapirejectRequest {
  reason?: string;
}

export interface EngineapirosterSetRequest {
  duckling?: string;
  role?: string;
}

export interface EngineapiskillNewRequest {
  name?: string;
  runnable?: boolean;
}

export interface EngineapiskillRunRequest {
  args?: Record<string, unknown>;
}

export interface EngineapitraceCheckResponse {
  errors?: Record<string, string>[];
}

export interface EngineapitranscriptResponse {
  markdown?: string;
}

export interface EngineapiverifyResponse {
  output?: string;
}

export interface ReportDelta {
  key?: string;
  n?: number;
  one_run?: boolean;
  pass_rate?: number;
  points_vs_baseline?: number;
}

export interface ReportReport {
  baseline?: string;
  by?: string;
  deltas?: ReportDelta[];
  resolutions?: ReportResolution[];
  rows?: ReportRow[];
  since?: string;
}

export interface ReportResolution {
  count?: number;
  kind?: string;
}

export interface ReportRow {
  builds?: number;
  cost_usd?: number;
  estimated?: boolean;
  failed?: number;
  key?: string;
  no_change_passes?: number;
  no_changes?: number;
  passed?: number;
  runs?: number;
  tokens?: number;
  unverified?: number;
  wallclock_ms?: number;
}

export interface RunlogBudgetLimits {
  tokens?: number;
  turns?: number;
  usd?: number;
  wallclock_s?: number;
}

export interface RunlogBudgetState {
  limit?: RunlogBudgetLimits;
  tokens?: number;
  turns?: number;
  usd?: number;
  wallclock_s?: number;
}

export interface RunlogDucklingSpend {
  calls?: number;
  cost_usd?: number;
  estimated?: boolean;
  tokens?: number;
}

export interface RunlogEvent {
  data?: Record<string, unknown>;
  duckling?: string;
  role?: string;
  round?: number;
  run_id?: string;
  seq?: number;
  ts?: string;
  turn?: number;
  type?: string;
}

export interface RunlogRun {
  accepted?: boolean;
  autonomy?: string;
  budget?: RunlogBudgetState;
  commit_sha?: string;
  dry_run?: boolean;
  ended_at?: string;
  failure?: string;
  gate?: string;
  id?: string;
  mode?: string;
  next?: string[];
  no_changes?: boolean;
  pending_data?: Record<string, unknown>;
  pending_kind?: string;
  pending_since?: string;
  project_id?: string;
  resolution?: string;
  roster?: Record<string, string>;
  spend?: Record<string, RunlogDucklingSpend>;
  stage?: string;
  started_at?: string;
  status?: string;
  stream?: boolean;
  task_id?: string;
  tests_modified?: boolean;
  tokens_estimated?: boolean;
  tree_snapshot?: string;
  unsafe_writes?: boolean;
  verdict?: string;
  wallclock_ms?: number;
  warning?: string;
}

export interface ServiceAcceptResult {
  commit_sha?: string;
}

export interface ServiceBenchSummary {
  cells?: number;
  errors?: number;
  passed?: number;
  stamp?: string;
  started_at?: string;
  suite?: string;
  suite_version?: number;
}

export interface ServiceBudgetView {
  max_tokens?: number;
  max_turns?: number;
  max_usd?: number;
  max_wallclock_s?: number;
}

export interface ServiceBugRequest {
  body?: string;
  reporter?: string;
  severity?: string;
  source?: string;
  title?: string;
}

export interface ServiceCandidateView {
  diff?: string;
  gate?: string;
  label?: string;
}

export interface ServiceDucklingView {
  caps?: ConfigCaps;
  color?: number;
  cost?: ConfigCost;
  id?: string;
  model?: string;
  notes?: string;
  params?: ConfigSamplingParams;
  provider?: string;
  roles?: string[];
}

export interface ServiceGateResult {
  command?: string;
  duration_s?: number;
  exit_code?: number;
  gate?: string;
  green?: boolean;
  output?: string;
}

export interface ServiceGateStatus {
  adoptable?: boolean;
  best_verdict?: string;
  command?: string;
  detected?: string;
  detected_command?: string;
  mode?: string;
}

export interface ServiceInitRequest {
  describe?: string;
  git_init?: boolean;
  name?: string;
  path?: string;
}

export interface ServiceModeDefaultsView {
  agent_max_turns?: number;
  ducklings?: Record<string, string[]>;
  role_turns?: Record<string, number>;
  rounds?: Record<string, number>;
  script_role_turns?: Record<string, number>;
  script_rounds?: Record<string, number>;
  seats?: Record<string, number>;
}

export interface ServiceProject {
  autonomy?: string;
  config?: ConfigProject;
  gate?: string;
  has_code?: boolean;
  id?: string;
  missing?: boolean;
  name?: string;
  path?: string;
}

export interface ServiceProviderView {
  api_key_env?: string;
  base_url?: string;
  headers?: Record<string, string>;
  id?: string;
  in_use?: string[];
  key_present?: boolean;
  kind?: string;
}

export interface ServiceReleaseRequest {
  bump?: string;
}

export interface ServiceReviewRequest {
  mode?: string;
  task_id?: string;
}

export interface ServiceRosterEntry {
  duckling?: string;
  role?: string;
  source?: string;
}

export interface ServiceRosterView {
  entries?: ServiceRosterEntry[];
  warning?: string;
}

export interface ServiceRunDetail {
  events?: RunlogEvent[];
  run?: RunlogRun;
}

export interface ServiceRunRequest {
  autonomy?: string;
  budget?: BudgetBudget;
  dry_run?: boolean;
  ducklings?: string[];
  mode?: string;
  no_stream?: boolean;
  parallel?: boolean;
  rounds?: number;
  task_id?: string;
  unsafe_writes?: boolean;
  verify?: string;
}

export interface ServiceSkillSummary {
  args?: SkillArg[];
  description?: string;
  name?: string;
  pending?: boolean;
  problems?: string[];
  runnable?: boolean;
  scope?: string;
  version?: number;
}

export interface ServiceStageRequest {
  adopt?: boolean;
  autonomy?: string;
  from?: string;
  mode?: string;
  revise?: string;
  rounds?: number;
  stage?: string;
  stream?: boolean;
}

export interface ServiceStatus {
  active_runs?: number;
  budget_spent_today?: number;
  stage_progress?: Record<string, string>;
  task_counts?: Record<string, number>;
}

export interface ServiceSuggestion {
  cost_per_mtok?: number;
  duckling?: string;
  evidence?: string;
  pass_rate?: number;
  role?: string;
  runs?: number;
}

export interface ServiceTaskView {
  blocked?: string;
  body?: string;
  complexity?: string;
  depends_on?: string[];
  id?: string;
  implements?: string[];
  milestone?: string;
  next?: string[];
  status?: string;
  title?: string;
}

export interface ServiceTestFirstRequest {
  duckling?: string;
  task_id?: string;
}

export interface SkillArg {
  name?: string;
  required?: boolean;
  type?: string;
}


/** Every endpoint, derived from the engine's route table. */
export const OPERATIONS = [
  { id: "BenchList", method: "GET", path: "/v1/bench" },
  { id: "Bench", method: "POST", path: "/v1/bench" },
  { id: "BenchStart", method: "POST", path: "/v1/bench/start" },
  { id: "BenchGet", method: "GET", path: "/v1/bench/{suite}/{stamp}" },
  { id: "BudgetDefaults", method: "GET", path: "/v1/defaults/budget" },
  { id: "BudgetDefaultsSet", method: "PUT", path: "/v1/defaults/budget" },
  { id: "ModeDefaults", method: "GET", path: "/v1/defaults/modes" },
  { id: "ModeDefaultsSet", method: "PUT", path: "/v1/defaults/modes" },
  { id: "DucklingList", method: "GET", path: "/v1/ducklings" },
  { id: "DucklingRemove", method: "DELETE", path: "/v1/ducklings/{id}" },
  { id: "DucklingSet", method: "PUT", path: "/v1/ducklings/{id}" },
  { id: "DucklingProbe", method: "POST", path: "/v1/ducklings/{id}/probe" },
  { id: "DucklingTest", method: "POST", path: "/v1/ducklings/{id}/test" },
  { id: "Engine", method: "GET", path: "/v1/engine" },
  { id: "get_events", method: "GET", path: "/v1/events" },
  { id: "Health", method: "GET", path: "/v1/health" },
  { id: "ProjectList", method: "GET", path: "/v1/projects" },
  { id: "ProjectInit", method: "POST", path: "/v1/projects" },
  { id: "ProjectForget", method: "DELETE", path: "/v1/projects/{id}" },
  { id: "ProjectGet", method: "GET", path: "/v1/projects/{id}" },
  { id: "ProjectUpdate", method: "PATCH", path: "/v1/projects/{id}" },
  { id: "ArtifactGet", method: "GET", path: "/v1/projects/{id}/artifacts/{kind}" },
  { id: "ArtifactPromote", method: "POST", path: "/v1/projects/{id}/artifacts/{kind}/promote" },
  { id: "ArtifactDiscard", method: "DELETE", path: "/v1/projects/{id}/artifacts/{kind}/proposal" },
  { id: "BugList", method: "GET", path: "/v1/projects/{id}/bugs" },
  { id: "BugAdd", method: "POST", path: "/v1/projects/{id}/bugs" },
  { id: "BugTriage", method: "POST", path: "/v1/projects/{id}/bugs/triage" },
  { id: "BugEdit", method: "PUT", path: "/v1/projects/{id}/bugs/{bug}" },
  { id: "BugPromote", method: "POST", path: "/v1/projects/{id}/bugs/{bug}/promote" },
  { id: "BugMove", method: "POST", path: "/v1/projects/{id}/bugs/{bug}/status" },
  { id: "ProjectGate", method: "GET", path: "/v1/projects/{id}/gate" },
  { id: "ProjectGateAdopt", method: "POST", path: "/v1/projects/{id}/gate" },
  { id: "GateRun", method: "POST", path: "/v1/projects/{id}/gate/run" },
  { id: "ReleaseList", method: "GET", path: "/v1/projects/{id}/releases" },
  { id: "ReleasePlan", method: "POST", path: "/v1/projects/{id}/releases" },
  { id: "ReleaseGet", method: "GET", path: "/v1/projects/{id}/releases/{version}" },
  { id: "ReleaseCut", method: "POST", path: "/v1/projects/{id}/releases/{version}/cut" },
  { id: "Report", method: "GET", path: "/v1/projects/{id}/report" },
  { id: "ReviewList", method: "GET", path: "/v1/projects/{id}/reviews" },
  { id: "ReviewStart", method: "POST", path: "/v1/projects/{id}/reviews" },
  { id: "ReviewGet", method: "GET", path: "/v1/projects/{id}/reviews/{task}" },
  { id: "RosterGet", method: "GET", path: "/v1/projects/{id}/roster" },
  { id: "RosterSet", method: "PUT", path: "/v1/projects/{id}/roster" },
  { id: "RosterSuggest", method: "GET", path: "/v1/projects/{id}/roster/suggest" },
  { id: "RosterApply", method: "POST", path: "/v1/projects/{id}/roster/suggest" },
  { id: "RunStart", method: "POST", path: "/v1/projects/{id}/runs" },
  { id: "SkillList", method: "GET", path: "/v1/projects/{id}/skills" },
  { id: "SkillNew", method: "POST", path: "/v1/projects/{id}/skills" },
  { id: "SkillGet", method: "GET", path: "/v1/projects/{id}/skills/{name}" },
  { id: "SkillRun", method: "POST", path: "/v1/projects/{id}/skills/{name}/run" },
  { id: "StageStart", method: "POST", path: "/v1/projects/{id}/stages/{stage}" },
  { id: "ProjectStatus", method: "GET", path: "/v1/projects/{id}/status" },
  { id: "TaskList", method: "GET", path: "/v1/projects/{id}/tasks" },
  { id: "TaskNext", method: "GET", path: "/v1/projects/{id}/tasks/next" },
  { id: "TaskRemove", method: "DELETE", path: "/v1/projects/{id}/tasks/{task}" },
  { id: "TestStart", method: "POST", path: "/v1/projects/{id}/tests" },
  { id: "TraceCheck", method: "GET", path: "/v1/projects/{id}/trace/check" },
  { id: "TraceShow", method: "GET", path: "/v1/projects/{id}/trace/{anyID}" },
  { id: "ProviderList", method: "GET", path: "/v1/providers" },
  { id: "ProviderRemove", method: "DELETE", path: "/v1/providers/{id}" },
  { id: "ProviderSet", method: "PUT", path: "/v1/providers/{id}" },
  { id: "RunList", method: "GET", path: "/v1/runs" },
  { id: "RunGet", method: "GET", path: "/v1/runs/{id}" },
  { id: "RunAbort", method: "POST", path: "/v1/runs/{id}/abort" },
  { id: "RunAccept", method: "POST", path: "/v1/runs/{id}/accept" },
  { id: "RunAnswer", method: "POST", path: "/v1/runs/{id}/answer" },
  { id: "RunBrief", method: "GET", path: "/v1/runs/{id}/brief" },
  { id: "RunCandidates", method: "GET", path: "/v1/runs/{id}/candidates" },
  { id: "RunDiff", method: "GET", path: "/v1/runs/{id}/diff" },
  { id: "RunLLM", method: "GET", path: "/v1/runs/{id}/llm" },
  { id: "RunReject", method: "POST", path: "/v1/runs/{id}/reject" },
  { id: "RunResume", method: "POST", path: "/v1/runs/{id}/resume" },
  { id: "RunTranscript", method: "GET", path: "/v1/runs/{id}/transcript" },
  { id: "RunVerify", method: "GET", path: "/v1/runs/{id}/verify" },
  { id: "post_shutdown", method: "POST", path: "/v1/shutdown" },
] as const;
